Models/Domain/FreelancerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Freelancers.Models.Domain
{
    public class FreelancerViewModel
    {
        public int ID { get; set; }
        [Required]
        public string? Username { get; set; }
        [Required]
        public string? Mail { get; set; }
        [Required]
        public string? PhoneNumber { get; set; }
        [Required]
        public string? Skillsets { get; set; }
        [Required]
        public string? Hobby { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace Freelancers.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/FreelancerController.cs
using Freelancers.Models.Domain;
using Freelancers.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Freelancers.Controllers
{
    public class FreelancerController : Controller
    {
        private readonly IUserService _userService;
        private readonly ILogger _logger; //implementing log4net....
        public FreelancerController(IUserService userService, ILogger<FreelancerController> logger) 
        {
            _userService = userService;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            //----- Get Access Token ----
            _logger.LogInformation("-----Program started-----");
            _logger.LogInformation("Get Access Token");

            try
            {
                var token_response = await _userService.GetAccessToken();
                var token = token_response.Token.ToString();
                TempData["AccessToken"] = token;

                var freelancerList = await _userService.GetFreelancers(token);
                return View(freelancerList);
            }
            catch (Exception ex)
            {

                throw new BadHttpRequestException("Bad Request", 400);
                
            }

            //return View();
        }



       
        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FreelancerViewModel newFreelancer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var data = await _userService.AddFreelancer(newFreelancer, TempData["AccessToken"].ToString());
                    TempData["SuccessMsg"] = "Freelancer (" + newFreelancer.Username + ") added successfully.";

                    _logger.LogInformation("Submit Data successfully");

                    return RedirectToAction(nameof(Index));
                }


                return View(newFreelancer);
            }
            catch
            {
                return View(newFreelancer);
            }
        }

        // GET: FreelancerController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var exist_model = await _userService.GetFreelancerById(id, TempData["AccessToken"].ToString());
            if (exist_model == null)
            {
                _logger.LogError("Data Not Found");
                return NotFound();
            }

            return View(exist_model);
        }

        // POST: FreelancerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, FreelancerViewModel updateFreelancer)
        {
            try
            {
                if (id != updateFreelancer.ID)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    var update_data = await _userService.UpdateFreelancer(id, updateFreelancer);
                    if (update_data != null)
                    {
                        TempData["SuccessMsg"] = "Freelancer updated successfully.";
                    }
                    else
                    {
                        TempData["ErrorMsg"] = "Error updating existing freelancer record";
                    }
                    
                    return RedirectToAction(nameof(Index));
                }

            }
            catch
            {
                return View(updateFreelancer);
            }
            return View(updateFreelancer);
        }

        // GET: FreelancerController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var check_freelancer =  await _userService.GetFreelancerById(id, TempData["AccessToken"].ToString());
            if (check_freelancer == null)
            {
                return NotFound();
            }

            return View(check_freelancer);
        }

        // POST: FreelancerController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {

                string delete_data =  await _userService.DeleteFreelancer(id);
                if (delete_data != null)
                {
                    TempData["SuccessMsg"] = "Freelancer Deleted successfully.";
                }
                else
                {
                    TempData["ErrorMsg"] = "Freelancer not found";
                }
                    return RedirectToAction(nameof(Index));
               
            }
            catch
            {
                
            }
            return View();

        }
    }
}

Views/Freelancer/Create.cshtml
@model Freelancers.Models.Domain.FreelancerViewModel

@{
    ViewData["Title"] = "Create";
}


<h2>Register a new Freelancer</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form id="form" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" id="email" class="form-control" placeholder="example@gmail.com" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" id="phn_no" placeholder="+60_ _ _ _ _ _ _ _ _" maxlength="13"  />
                <span id="phn-no-error" asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Skillsets" class="control-label"></label>
                <input asp-for="Skillsets" class="form-control" />
                <span asp-validation-for="Skillsets" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hobby" class="control-label"></label>
                <input asp-for="Hobby" class="form-control" />
                <span asp-validation-for="Hobby" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" id="submit_btn" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
        <script type="text/javascript">
            $(document).ready(function () {
                $('#submit_btn').click(function (e) {
                    e.preventDefault();

                    if ($('#phn_no').val() != "") {
                        var tel = telephoneCheck($('#phn_no').val());
                    } else {
                    alert("Please Enter Telephone Number");
                    }
                    if ($('#email').val() != "") {
                      var email = validateEmail($('#email').val());
                    }else{
                    alert("Please Enter Email");
                    }
                    if (tel == true && email == true) {
                     $("#form").submit();
                    }
                    
                
                
                })
            function telephoneCheck(str) {
                var isphone = /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/im.test(str);
                if (!isphone) {
                    alert("Invalid Telephone Number");
                    return false;
                } else {
                    return true;
                }
                
                //+31636363634
            }
            function validateEmail(email) {
                var emailReg = /^([a-zA-Z0-9_.+-])+\@@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/.test(email);
                if (!emailReg) {
                    alert("Invalid Email Address");
                    return false;
                }else{
                    return true;
                }
            }
            
            });
        </script>

}

Views/Freelancer/Delete.cshtml
@model Freelancers.Models.Domain.FreelancerViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />

     <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Skillsets)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Skillsets)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Hobby)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Hobby)
        </dd>
    </dl> 
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Freelancer/Edit.cshtml
@model Freelancers.Models.Domain.FreelancerViewModel

@{
    ViewData["Title"] = "Edit";
}


<h2>Update Freelancer Details</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form id="form" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mail" class="control-label"></label>
                <input asp-for="Mail" id="email" class="form-control" placeholder="example@gmail.com" />
                <span asp-validation-for="Mail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" id="phn_no" placeholder="+60_ _ _ _ _ _ _ _ _" maxlength="13" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Skillsets" class="control-label"></label>
                <input asp-for="Skillsets" class="form-control" />
                <span asp-validation-for="Skillsets" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Hobby" class="control-label"></label>
                <input asp-for="Hobby" class="form-control" />
                <span asp-validation-for="Hobby" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" id="submit_btn" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#submit_btn').click(function (e) {
                e.preventDefault();

                if ($('#phn_no').val() != "") {
                    var tel = telephoneCheck($('#phn_no').val());
                } else {
                    alert("Please Enter Telephone Number");
                }
                if ($('#email').val() != "") {
                    var email = validateEmail($('#email').val());
                } else {
                    alert("Please Enter Email");
                }
                if (tel == true && email == true) {
                    $("#form").submit();
                }



            })
            function telephoneCheck(str) {
                var isphone = /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/im.test(str);
                if (!isphone) {
                    alert("Invalid Telephone Number");
                    return false;
                } else {
                    return true;
                }

                //+31636363634
            }
            function validateEmail(email) {
                var emailReg = /^([a-zA-Z0-9_.+-])+\@@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/.test(email);
                if (!emailReg) {
                    alert("Invalid Email Address");
                    return false;
                } else {
                    return true;
                }
            }

        });
    </script>
}

Views/Freelancer/Index.cshtml
@model IEnumerable<Freelancers.Models.Domain.FreelancerViewModel>

@{
    ViewData["Title"] = "Index";
}


<div class="container shadow p-5">

    @if (TempData["SuccessMsg"] != null)
    {
        <div class="alert alert-success" role="alert">
            @TempData["SuccessMsg"]
        </div>
    }
    else if (TempData["ErrorMsg"] != null)
    {
        <div class="alert alert-danger" role="alert">
            @TempData["ErrorMsg"]
        </div>
        
    }   


    <h1 class="text-center">Freelancer List</h1>

    <div class="col mb-3">
        <a asp-controller="Freelancer" asp-action="Create" class="btn btn-primary">Add New Freelancer</a>
    </div>

    <table id="freelancers" class="table table-light table-hover" class="display" style="width:80%">
        <thead class="table-light">
            <tr>
                <th scope="col">Username</th>
                <th scope="col">Mail</th>
                <th scope="col">PhoneNumber</th>
                <th scope="col">Skillsets</th>
                <th scope="col">Hobby</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Username
                    </td>
                    <td>
                        @item.Mail
                    </td>
                    <td>
                        @item.PhoneNumber
                    </td>
                    <td>
                        @item.Skillsets
                    </td>
                    <td>
                        @item.Hobby
                    </td>
                  
                    <td>
                        <a asp-controller="Freelancer" asp-action="Edit" asp-route-id="@item.ID" class=" btn btn-success">Edit</a>
                        <a asp-controller="Freelancer" asp-action="Delete" asp-route-id="@item.ID" class="btn btn-primary">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    
</div>
@section Scripts {
    <script type="text/javascript">
        $(document).ready(function () {

            $('#freelancers').DataTable({
                processing: true,
                ordering: true,
                paging: true,
                searching: true,
                pagingType: 'full_numbers'

            });
            
        });
    </script>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Freelancers</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Freelancers.styles.css" asp-append-version="true" />
    <!-- datatables css-->
    <link href="~/lib/datatables/css/jquery.dataTables.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/dataTables.bootstrap4.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Freelancer" asp-action="Index">Freelancers</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Freelancers 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- datatables js-->
    <script src="~/lib/datatables/js/jquery.dataTables.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>